version: '3.8'

services:
  amm-near-agent:
    build:
      context: ../..
      dockerfile: apps/amm-near-agent/Dockerfile
    container_name: amm-near-agent
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./data
        target: /app/apps/amm-near-agent/data
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"